clean: true

module: SimpleMDM
module_version: 0.1.0

swift_version: 4.2

github_url: https://github.com/guillaumealgis/simplemdm-swift
github_file_prefix: https://github.com/guillaumealgis/simplemdm-swift/tree/0.1.0

author: Guillaume Algis
author_url: http://twitter.com/guillaumealgis

output: docs
theme: apple



custom_categories:
  - name: SimpleMDM
    children:
    - SimpleMDM

  - name: Resources
    children:
    - Account
    - App
    - App.ManagedConfig
    - AppGroup
    - CustomAttribute
    - CustomConfigurationProfile
    - Device
    - Device.CustomAttributeValue
    - DeviceGroup
    - InstalledApp
    - PushCertificate
    - Resource

  - name: Resources Types
    children:
    - UniqueResource
    - IdentifiableResource
    - GettableResource
    - ListableResource

  - name: Relationships
    children:
    - RelatedToOne
    - RelatedToMany
    - RelatedToManyNested

  - name: Cursor
    children:
    - Cursor
    - NestedResourceCursor
    - CursorLimit

  - name: Errors
    children:
    - InternalError
    - NetworkError
    - SimpleMDMError
