clean: true

module: SimpleMDM
module_version: 0.5.0

swift_version: 5.0.1

github_url: https://github.com/guillaumealgis/simplemdm-swift
github_file_prefix: https://github.com/guillaumealgis/simplemdm-swift/tree/0.5.0

root_url: https://guillaumealgis.github.io/SimpleMDM-Swift

author: Guillaume Algis
author_url: http://twitter.com/guillaumealgis

output: docs
theme: apple



custom_categories:
  - name: SimpleMDM
    children:
    - SimpleMDM

  - name: Resources
    children:
    - Account
    - App
    - AppGroup
    - CustomAttribute
    - CustomConfigurationProfile
    - Device
    - DeviceGroup
    - InstalledApp
    - PushCertificate
    - Resource

  - name: Resources Types
    children:
    - UniqueResource
    - IdentifiableResource
    - GettableResource
    - ListableResource

  - name: Fields Types
    children:
    - Version

  - name: Relationships
    children:
    - RelatedToOne
    - RelatedToMany
    - RelatedToManyNested

  - name: Cursor
    children:
    - Cursor
    - NestedResourceCursor
    - CursorLimit

  - name: Errors
    children:
    - InternalError
    - NetworkError
    - SimpleMDMError

  - name: Misc
    children:
    - Result
    - CompletionClosure
    - RemoteCollection
