included:
  - Sources
  - Tests

disabled_rules:
  - line_length

  # With Xcode 11.0, SourceKit has a bug which makes swiftlint (0.35.0) crash
  # for some combinations or rules and sources.
  # We're disabling theses rules for now:
  # - no_space_in_method_call
  # - reduce_into
  # And in the opt-in rules:
  # - multiline_function_chains
  # - trailing_closure
  # - unused_declaration
  #
  # Bug follow-up at:
  # - https://github.com/realm/SwiftLint/issues/2793
  # - https://bugs.swift.org/browse/SR-11099
  - no_space_in_method_call
  - reduce_into


analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

opt_in_rules:
  # - multiline_function_chains
  # - trailing_closure
  # - unused_declaration

  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_grouping_extension
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# configurable rules
identifier_name:
  excluded: [i, id]
type_name:
  excluded: [ID]
number_separator:
  minimum_length: 5
modifier_order:
  preferred_modifier_order: [acl, override]
implicit_return:
  included: [getter, closure]

excluded:
  - Package.swift
