language: swift
osx_image: xcode11

xcode_project: SimpleMDM-Swift.xcodeproj
xcode_scheme: SimpleMDM

addons:
  homebrew:
    packages:
    - swiftformat
    - swiftlint
    - carthage
    update: true

install:
  - carthage update

matrix:
  include:

  - name: "macOS 10.15"
    xcode_sdk: macosx10.15
    after_success:
      - bash <(curl -s https://codecov.io/bash) -J SimpleMDM

  - name: "iOS 13.0"
    xcode_sdk: iphoneos13.0
    xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11

  - name: "tvOS 13.0"
    xcode_sdk: appletvos13.0
    xcode_destination: platform=tvOS Simulator,OS=13.0,name=Apple TV 4K

  - name: "watchOS 6.0"
    xcode_sdk: watchos6.0
    xcode_destination: platform=watchOS Simulator,OS=6.0,name=Apple Watch Series 5 - 40mm
    # We can't run tests for watchOS, just ensure the project builds fine
    script: set -o pipefail && xcodebuild -project SimpleMDM-Swift.xcodeproj -scheme SimpleMDM -sdk watchos6.0 build | xcpretty

  - name: "linting"
    script:
      - swiftformat --version
      - swiftformat --config .swiftformat --lint .
      - swiftlint version
      - swiftlint --strict

  - name: "Cocoapods"
    script:
      - gem install cocoapods
      - pod repo update
      - pod lib lint --verbose --allow-warnings --fail-fast SimpleMDM-Swift.podspec
