language: swift
osx_image: xcode11

addons:
  homebrew:
    packages:
    - swiftformat
    - swiftlint
    update: true

matrix:
  include:

  - name: "macOS 10.12"
    script: >-
      xcrun swift test --parallel --verbose
      -Xswiftc "-warnings-as-errors"
      -Xswiftc "-sdk" -Xswiftc $(xcrun --sdk macosx --show-sdk-path)
      -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.12"

  - name: "macOS 10.15"
    script: >-
      xcrun swift test --parallel --verbose --enable-code-coverage
      -Xswiftc "-warnings-as-errors"
      -Xswiftc "-sdk" -Xswiftc $(xcrun --sdk macosx --show-sdk-path)
      -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.15"
    after_success:
      - xcrun llvm-cov export -format="lcov" $(find . -name 'SimpleMDM-SwiftPackageTests.xctest')/Contents/MacOS/SimpleMDM-SwiftPackageTests -instr-profile $(find . -name 'default.profdata') > info.lcov
      - bash <(curl -s https://codecov.io/bash) -J '^SimpleMDM$'

  - name: "iOS 13.0"
    script: >-
      xcrun swift test --parallel --verbose
      -Xswiftc "-warnings-as-errors"
      -Xswiftc "-sdk" -Xswiftc $(xcrun --sdk iphonesimulator --show-sdk-path)
      -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"

  - name: "tvOS 13.0"
    script: >-
      xcrun swift test --parallel --verbose
      -Xswiftc "-warnings-as-errors"
      -Xswiftc "-sdk" -Xswiftc $(xcrun --sdk appletvsimulator --show-sdk-path)
      -Xswiftc "-target" -Xswiftc "x86_64-apple-tvos13.0-simulator"

  - name: "watchOS 6.0"
    # We can't run tests for watchOS, just ensure the project builds fine
    script: >-
      xcrun swift build --verbose
      -Xswiftc "-warnings-as-errors"
      -Xswiftc "-sdk" -Xswiftc $(xcrun --sdk watchsimulator --show-sdk-path)
      -Xswiftc "-target" -Xswiftc "i386-apple-watchos6.0-simulator"

  - name: "linting"
    script:
      - swiftformat --version
      - swiftformat --config .swiftformat --lint .
      - swiftlint version
      - swiftlint --strict

  - name: "Cocoapods"
    script:
      - gem install cocoapods
      - pod repo update
      - pod lib lint --verbose --allow-warnings --fail-fast SimpleMDM-Swift.podspec
