name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: 'Sources'
          format: 'html'
          module-name: 'SimpleMDM-Swift'
          output: 'Documentation'
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .build/documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
